data-submission:
  - all: ['model-output/**/*.csv']
 
code:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'

model-metadata:
  - all: ['model-metadata/**/*.yml', 'model-metadata/**/*.yaml']

-documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'